### PR TITLE
Modify ssd1322 driver to use gamma + added precharge voltage device file.

### PR DESCRIPTION
**Pull request by tlubke**
- Made /sys/class/graphics/fbX/gamma accessible to all users.
 - Added /sys/class/graphics/fbX/precharge, accessible by all.
 - Added related "precharge" struct fields for fbtft core lib.
 - *Note: Used a macro trick in fbtft-sysfs.c to allow octal
          permissions of 0666 to "gamma" and "precharge.

### CODE REVIEW

**Comment by tlubke** [comment]
There will be a related PR to monome/norns up here soon.

**Review by tehn — COMMENTED** [review]
Wow, thank you.

I'm curious, how does this look? Is it effective in practice?

**Comment by tehn** [comment]
Just to note, changing the kernel means having to deliver a new kernel via the update mechanism, which is a heavy lift (would prefer to keep updates very small and less error prone). We may need to instead make this an optional upgrade by providing new disk images.

**Comment by tlubke** [comment]
@tehn 

> I'm curious, how does this look? Is it effective in practice?
Yes, I definitely see a huge improvement in level distinction. I like to set it around 2.0 or 2.14 gamma, but even as high as 3.0 is an improvement. In the norns code, I added a DISPLAY settings page to easily change it (defaults settings are how current norns looks). I've had a hard time capturing the difference on camera, but I might try again and mess around with the ambient lighting.

> Just to note, changing the kernel means having to deliver a new kernel via the update mechanism, which is a heavy lift (would prefer to keep updates very small and less error prone). We may need to instead make this an optional upgrade by providing new disk images.

I figured this might be the case. I have some more screen improvements that I'm working on that might justify using the update mechanism once they're all done --
1. Implementing 4-bit Alpha format in Cairo: This is pretty close to being done, not sure how long it will take to be merged into the main branch though. Once that's in, I can change the cairo format on norns from ARGB32, to A4 which theoretically could cut down on resources used by screen operations.
2. Screen driver 15 FPS to 60 FPS: With some processing reclaimed from the above, hopefully I could change the screen to 60 FPS without any noticeable differences to CPU or battery usage to today.

I believe both will require more changes to the driver. 1, because of the change in vram size. 2, because of changes that will need to be made to the device registers.

In the meantime, I think disk images would make sense as an optional upgrade. I was even planning to figure out how to do that to get some feedback on the changes.

**Comment by tlubke** [comment]
see: https://github.com/monome/norns/pull/1582

**Comment by tehn** [comment]
Ah, the 60fps has been a dream of mine, though it never manages to climb very high on the priority list. I take it the driver gets reworked to update only "dirty" zones of the screen by moving the refresh rectangle around? I remember seeing this approach (in linux specifically) years ago, but lost the link/reference. (It's pretty trivial at the low level, but the framebuffer interface was a little opaque to me...)

4 bit alpha in Cairo would likewise be fantastic.

Creating a modified disk image (without starting from scratch, which is a long process) basically means downloading the existing disk image and copying the new kernel into the right place. Then packing the image back up. Let me know if you need help with this.

pinging @ngwese for comment, but I'm happy to merge this

**Review by tehn — APPROVED** [review]

**Comment by ngwese** [comment]
I will look at this in more detail in the next day or two but on initial inspection I'm _**not inclined to merge**_ this without further discussion on longer term plans because this change is not isolated to just the `ssd1322` driver, it is changing the `fbtft` core itself.

Are the changes to the fbtftf core in this PR derived from some upstream source? a newer kernel? or are they entirely new? Are there any plans to submit these changes to the mainline or raspberrypi kernel trees?

Other considerations which come to mind include:

- The fbtft core has gone through a decent amount of churn in the last several kernels in order to adapt to changes in the gpio system within the kernel. Changing the fbtft core will make rolling forward to newer kernels even more difficult than it currently is because it makes the norns kernel a distinct fork. Up to this point I believe all of the norns kernel changes are configuration related, back porting of upstream patches, or adding code for hardware specific to norns itself.
- I don't know how the kernel is maintained for fates devices but my impression is that it is largely a stock RPI kernel with dtb tweaks additional kernel modules installed; this change would need to be adopted there as well if the desire was to avoid fragmentation
- If matron _requires_ these sysfs change to function correctly when targeting fbtft then the ability to get the norns stack running easily on other linux machines decreases.

**Comment by tlubke** [comment]
@ngwese 

> Are the changes to the fbtftf core in this PR derived from some upstream source? a newer kernel? or are they entirely new? Are there any plans to submit these changes to the mainline or raspberrypi kernel trees?

These changes are entirely new. I didn't have any plans to submit these changes to mainline/rpi kernel trees, but I think without the octal permission trick in sysfs, it would make an acceptable PR since the additions are all optional per-driver. Without the octal permissions however, we will need another way of writing to /sys/class/graphics/... with Matron in order for the settings to be changed by norns in real time.

Another option is to drop the pre-charge voltage additions all together, then this PR would only touch the sd1322 driver.

> Other considerations which come to mind include:

I've read all of these carefully, and I agree it's a good idea to avoid fragmentation between fates and norns, and future kernel changes.

**Comment by tlubke** [comment]
see: https://github.com/monome/norns/pull/1583

**Comment by tlubke** [comment]
@tehn 

I made an image here: https://github.com/tlubke/norns/releases/tag/220306

Could I share this on lines, or wait for more discussion to take place first?

**Comment by tehn** [comment]
I agree that it's important to design for maintainability--- thanks @ngwese for evaluating

@tlubke What do we actually gain by a configurable precharge? I've never touched this parameter dynamically in the past. It'd certainly simplify everything about this proposal to limit the scope to gamma. What do you think?

Are you on the norns discord? I might suggest sharing there initially, rather than on the forum. Engagement tends to be higher for beta-testing there.

**Comment by tlubke** [comment]
@tehn 

> @tlubke What do we actually gain by a configurable precharge? I've never touched this parameter dynamically in the past. It'd certainly simplify everything about this proposal to limit the scope to gamma. What do you think?

Precharge has an effect on the overall level, and especially effects the jump from screen level 0 to screen level 1. I found that a value of 16 looked more "balanced" with an adjusted gamma than the value of 31 it was at initially. However, in bright daylight, it was kind of hard to see. I figured it might be nice to be adjustable.

I can see the argument for reducing the scope of changes by removing configurable precharge, however I think we still need to find a way around the sysfs permissions. Is there a way to give certain functions in matron elevated privileges? I'm not sure what kind of _nefarious deeds_ could happen if elevated privileges were given to the whole program.

> Are you on the norns discord? I might suggest sharing there initially, rather than on the forum. Engagement tends to be higher for beta-testing there.

I am on there, but I haven't been active in a long while. I'll make a post on there today though.

**Comment by ngwese** [comment]
I've thought about this some more and the changes to the `fbtft` core are small enough that the work to integrate with newer kernels is probably manageable.

I would like to advocate that:
- The work to enable higher FPS is completed/tested as well before a new kernel is released to the masses
- The user space (matron) side of the gamma control disables itself if the kernel functionality is not available so that fates devices, DIY pi based setups, and docker/desktop builds don't break if they lack the kernel additions

/cc @okyeron

**Comment by tehn** [comment]
i agree with @ngwese.

it also brings up further needed discussion about update mechanisms--- it no longer makes sense to bundle kernels with the update, since we grew from 2 possible kernels to 5. i'll have to investigate a new mechanism for kernel updates.

**Comment by ngwese** [comment]
i think the right approach might be proper .deb packages but that is a level of effort that i don’t have the cycles for at the moment.

**Comment by tlubke** [comment]
sorry I've been away from this conversation for a while. my norns had been out for repair for some time. I started a new issue to try to reorganize my thoughts and the progress that has been made in these PRs https://github.com/monome/norns/issues/1600.

the last thing I accomplished was compiling cairo libs on norns to support A4, but I don't think I installed/linked them correctly afterwards when building matron. could use some assistance on that process since a system search showed a lot of cairo files in different places.

EDIT: Got cairo compile/link figured out. `apt-get remove libcairo2-dev`, then `autogen.sh; sudo make install` in a cloned cairo directory on my branch. Might have been an oddity, but had to reinstall `libpixman-1-dev` and `libpixman-1-0` to fix a seg fault in matron.

**Comment by tlubke** [comment]
Closing in favor of userspace SPI screen.

**Pull request closed without merging**
